name: Hash Functions
on: push
jobs:
    hash:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set HASH variable
              run: echo "HASH=${{ hashFiles('.github/workflows/*.yml') }}" >> $GITHUB_ENV
            - run: echo "${HASH}"