name: Context
on: push
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Actor: ${{ github.actor }}"
                echo "Repository: ${{ github.repository }}"
                echo "Event Name: ${{ github.event_name }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Run ID: ${{ github.run_id }}"