name: Job Summury
on: push
jobs:
    log:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "## Shohiiiiiii Title :rocket:" >> "${GITHUB_STEP_SUMMARY}"
                echo " - first line " >> "${GITHUB_STEP_SUMMARY}"
                echo """
                > [!IMPORTANT]
                > shohiiiiiii
                """ >> "${GITHUB_STEP_SUMMARY}"