name: Job Summury
on: push
jobs:
    log:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "## Shohiiiiiii Title :rocket:" >> "${GITHUB_STEP_SUMMURY}"
                echo " - first line " >> "${GITHUB_STEP_SUMMURY}"
                echo "- shohiiiiiii" >> "${GITHUB_STEP_SUMMURY}"