name: Literals
on: push
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - run: privemtenv | grep 'LITERAL_'
              env:
                LITERAL_NULL: ${{ null }}
                LITERAL_BOOLEAN: ${{ true }}
                LITERAL_NUMBER: ${{ 1234 }}
                LITERAL_STRING: ${{ 'STRING でっせ' }}
                LITERAL_OMIT_STRING: World Shohi