name: Manual
on:
    workflow_dispatch:
        inputs:
            greeting:
                type: string
                default: Shoiiiiiii
                required: true
                description: A Cheerful takky
jobs:
    runs:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ inputs.greeting }}"